services:
  - type: web
    name: agribridge-api
    env: node
    region: oregon
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: NODE_ENV
        value: production
