
export type UserRole = 'FARMER' | 'BUYER' | 'LOGISTICS' | 'WAREHOUSE' | 'ADMIN';

export interface User {
  id: string;
  name: string;
  role: UserRole;
  location: string;
  avatar: string;
}

export interface Country {
  code: string;
  name: string;
  currency: string;
  flag: string;
  locations: string[];
  coordinates: {
    lat: number;
    lng: number;
  };
}

export interface Product {
  id: string;
  farmerId: string;
  farmerName: string;
  name: string;
  category: 'Vegetables' | 'Fruits' | 'Grains' | 'Tubers';
  price: number;
  unit: string;
  quantity: number;
  harvestDate: string;
  description: string;
  imageUrl: string;
  location: string;
}

export interface TransportRequest {
  id: string;
  farmerId: string;
  farmerName: string;
  origin: string;
  destination: string;
  originCoords?: [number, number];
  destinationCoords?: [number, number];
  goodsType: string;
  weightKg: number;
  status: 'PENDING' | 'ACCEPTED' | 'COMPLETED';
  priceOffer: number;
  assignedProviderId?: string;
  assignedProviderName?: string;
}

export interface LogisticsProvider {
  id: string;
  name: string;
  vehicleType: string;
  plateNumber: string;
  location: string;
  rating: number;
  completedTrips: number;
  imageUrl: string;
  baseRatePerKm: number;
}

export interface FleetVehicle {
  id: string;
  name: string;
  plate: string;
  capacity: string;
  location: string;
  status: 'Available' | 'Maintenance' | 'On Trip';
}

export interface StorageFacility {
  id: string;
  ownerId: string;
  name: string;
  type: 'COLD_ROOM' | 'WAREHOUSE' | 'SILO';
  location: string;
  capacityKg: number;
  availableKg: number;
  pricePerKgDaily: number;
  temperature?: number; // for cold rooms
  imageUrl: string;
}

export interface Order {
  id: string;
  buyerId: string;
  farmerId: string;
  productName: string;
  amount: number;
  status: 'PROCESSING' | 'SHIPPED' | 'DELIVERED';
  date: string;
}

export interface MarketPrice {
  crop: string;
  market: string;
  price: number;
  trend: 'UP' | 'DOWN' | 'STABLE';
}

export interface CartItem extends Product {
  cartQuantity: number;
}

export interface Transaction {
  id: string;
  type: 'DEPOSIT' | 'WITHDRAWAL' | 'PAYMENT' | 'INCOME';
  amount: number;
  date: string;
  status: 'COMPLETED' | 'PENDING' | 'FAILED';
  description: string;
  reference: string;
}

export type Language = 'en' | 'sw' | 'fr' | 'ar' | 'pt' | 'am';

export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    marketplace: "Marketplace",
    logistics: "Logistics",
    storage: "Storage Hub",
    aiAssistant: "Agri-Advisor AI",
    profile: "My Profile",
    email: "Email",
    phone: "Phone",
    listings: "Listings",
    fleetTrips: "Fleet & Trips",
    facilities: "Facilities",
    orders: "Orders",
    newListing: "New Listing",
    myListings: "My Listings",
    welcome: "Welcome back",
    role: "Current Role",
    switchTo: "Switch to",
    price: "Price",
    quantity: "Quantity",
    harvestDate: "Harvest Date",
    shelfLife: "Est. Shelf Life",
    bookTransport: "Book Transport",
    marketTrends: "Market Trends",
    logout: "Logout",
    settings: "Settings",
    country: "Country",
    about: "About & Contact",
    // Logistics
    logisticsHub: "Logistics Hub",
    requestTransport: "Request Transport",
    addVehicle: "Add Vehicle",
    activeRequests: "Active Requests",
    myFleet: "My Fleet",
    listView: "List View",
    mapView: "Map View",
    activeOrders: "Active Orders",
    noRequests: "No active transport requests found.",
    goodsType: "Goods Type",
    from: "From",
    to: "To",
    cargo: "Cargo",
    assignedTo: "Assigned to",
    viewRoute: "View Route",
    hideMap: "Hide Map",
    acceptJob: "Accept Job",
    accepted: "Accepted",
    processing: "Processing",
    status: "Status",
    pickupLocationPreview: "Pickup Location Preview",
    poweredBy: "Powered by Google Maps",
    capacity: "Capacity",
    currentLocation: "Current Location",
    edit: "Edit",
    schedule: "Schedule",
    requestTransportTitle: "Request Transport",
    nearestProviders: "Nearest Providers",
    originPickup: "Origin (Pickup)",
    destination: "Destination",
    estWeight: "Est. Weight (kg)",
    findTransporters: "Find Transporters",
    findingDrivers: "Finding Nearby Drivers...",
    foundProviders: "Found providers near",
    vehicle: "Vehicle",
    rate: "Rate",
    selectRequest: "Select & Request",
    backToSearch: "Back to Search",
    editVehicle: "Edit Vehicle",
    addNewVehicle: "Add New Vehicle",
    vehicleModel: "Vehicle Model",
    licensePlate: "License Plate",
    baseLocation: "Base Location",
    updateVehicle: "Update Vehicle",
    addVehicleToFleet: "Add Vehicle to Fleet",
    saving: "Saving...",
    updateStatus: "Update Status",
    changeStatusFor: "Change current status for",
    available: "Available",
    onTrip: "On Trip",
    maintenance: "Maintenance",
    // Storage
    storageHub: "Storage Hub",
    storageSubtitle: "Find cold rooms and warehouses to prevent spoilage in",
    addNewFacility: "Add New Facility",
    findNearestStorage: "Find Nearest Storage",
    produceType: "Produce Type",
    allCategories: "All Categories",
    perishable: "Vegetables/Fruits (Cold Room)",
    dry: "Grains/Tubers (Dry Storage)",
    quantityToStore: "Quantity to Store (kg)",
    yourLocation: "Your Location",
    searchFacilities: "Search Facilities",
    searching: "Searching...",
    noFacilities: "No storage facilities found matching your criteria.",
    clearFilters: "Clear filters",
    booked: "Booked",
    free: "free",
    perKgDay: "per kg / day",
    manage: "Manage",
    reserved: "Reserved",
    bookSpace: "Book Space",
    bookStorageSpace: "Book Storage Space",
    startDate: "Start Date",
    durationDays: "Duration (Days)",
    storageNote: "Please ensure your produce is packed correctly.",
    cancel: "Cancel",
    confirmBooking: "Confirm Booking",
    booking: "Booking...",
    facilityName: "Facility Name",
    saveFacility: "Save Facility",
    manageFacility: "Manage Facility",
    totalCapacity: "Total Capacity",
    availableSpace: "Available Space (kg)",
    resetMax: "Reset Max",
    updateFacility: "Update Facility",
    // Profile
    myActiveListings: "My Active Listings",
    items: "Items",
    recentSalesHistory: "Recent Sales History",
    noSales: "No sales yet.",
    item: "Item",
    date: "Date",
    amount: "Amount",
    fleetStatus: "Fleet Status",
    tripHistory: "Trip History",
    noTrips: "No trips completed yet.",
    route: "Route",
    earnings: "Earnings",
    recentOrderHistory: "Recent Order History",
    noOrders: "No orders yet.",
    managedFacilities: "Managed Facilities",
    editProfile: "Edit Profile",
    joined: "Joined",
    contactInfo: "Contact Information",
    emailAddress: "Email Address",
    phoneNumber: "Phone Number",
    performanceStats: "Performance Stats",
    orderCompletion: "Order Completion",
    avgResponse: "Avg. Response",
    userRating: "User Rating",
    onPlatform: "On Platform",
    verification: "Verification",
    emailVerified: "Email Verified",
    phoneVerified: "Phone Verified",
    identityVerified: "Identity Verified (KYC)",
    premiumMember: "Premium Member",
    overview: "Overview",
    activity: "Activity",
    reviews: "Reviews",
    displayName: "Display Name",
    bio: "Bio",
    enhanceWithAI: "Enhance with AI",
    saveChanges: "Save Changes",
    // About & Contact
    aboutTitle: "About AgriBridge Africa",
    aboutText: "AgriBridge is a comprehensive digital marketplace and logistics platform designed to bridge the gap between smallholder farmers, buyers, and transport services.",
    ourMission: "Our Mission",
    missionText: "To minimize post-harvest loss and increase farmer income through technology.",
    trustSafety: "Trust & Safety",
    trustText: "Verified users, secure payments, and transparent logistics tracking.",
    panAfrican: "Pan-African",
    panAfricanText: "Connecting markets across borders to foster regional trade.",
    getInTouch: "Get in Touch",
    messageSent: "Message Sent!",
    thankYouContact: "Thank you for contacting us. We will get back to you shortly.",
    sendAnother: "Send Another",
    fullName: "Full Name",
    subject: "Subject",
    selectTopic: "Select a topic...",
    technicalSupport: "Technical Support",
    partnershipInquiry: "Partnership Inquiry",
    billingQuestion: "Billing Question",
    other: "Other",
    message: "Message",
    howCanWeHelp: "How can we help you?",
    sendMessage: "Send Message",
    sending: "Sending...",
    headquarters: "Headquarters",
    emailUs: "Email Us",
    callCenter: "Call Center",
    frequentlyAsked: "Frequently Asked",
    // Cart
    yourCart: "Your Cart",
    cartEmpty: "Your cart is empty",
    startShopping: "Start Shopping",
    subtotal: "Subtotal",
    serviceFee: "Service Fee",
    total: "Total",
    proceedToCheckout: "Proceed to Checkout"
  },
  sw: {
    dashboard: "Dashibodi",
    marketplace: "Soko",
    logistics: "Usafirishaji",
    storage: "Hifadhi",
    aiAssistant: "Mshauri wa Kilimo AI",
    profile: "Wasifu Wangu",
    newListing: "Orodha Mpya",
    myListings: "Orodha Zangu",
    welcome: "Karibu tena",
    role: "Nafasi ya Sasa",
    switchTo: "Badilisha kwenda",
    price: "Bei",
    quantity: "Kiasi",
    harvestDate: "Tarehe ya Mavuno",
    shelfLife: "Maisha ya Rafu",
    bookTransport: "Weka Usafiri",
    marketTrends: "Mwenendo wa Soko",
    logout: "Ondoka",
    settings: "Mipangilio",
    country: "Nchi",
    about: "Kuhusu & Mawasiliano",
    // Logistics
    logisticsHub: "Kituo cha Usafirishaji",
    requestTransport: "Omba Usafiri",
    addVehicle: "Ongeza Gari",
    activeRequests: "Maombi yanayoendelea",
    myFleet: "Meli Yangu",
    listView: "Orodha",
    mapView: "Ramani",
    activeOrders: "Oda Zinazoendelea",
    noRequests: "Hakuna maombi ya usafiri yanayoendelea.",
    goodsType: "Aina ya Bidhaa",
    from: "Kutoka",
    to: "Kwenda",
    cargo: "Mzigo",
    assignedTo: "Imepewa",
    viewRoute: "Angalia Njia",
    hideMap: "Ficha Ramani",
    acceptJob: "Kubali Kazi",
    accepted: "Imekubaliwa",
    processing: "Inashughulikiwa",
    status: "Hali",
    pickupLocationPreview: "Hakiki Mahali pa Kuchukua",
    poweredBy: "Inaendeshwa na Ramani za Google",
    capacity: "Uwezo",
    currentLocation: "Mahali pa Sasa",
    edit: "Hariri",
    schedule: "Ratiba",
    requestTransportTitle: "Omba Usafiri",
    nearestProviders: "Watoa Huduma wa Karibu",
    originPickup: "Asili (Kuchukua)",
    destination: "Nenda",
    estWeight: "Uzito (kg)",
    findTransporters: "Tafuta Wasafirishaji",
    findingDrivers: "Inatafuta Madereva wa Karibu...",
    foundProviders: "Watoa huduma wamepatikana karibu na",
    vehicle: "Gari",
    rate: "Kiwango",
    selectRequest: "Chagua & Omba",
    backToSearch: "Rudi Kutafuta",
    editVehicle: "Hariri Gari",
    addNewVehicle: "Ongeza Gari Jipya",
    vehicleModel: "Mfano wa Gari",
    licensePlate: "Nambari ya Leseni",
    baseLocation: "Mahali pa Msingi",
    updateVehicle: "Sasisha Gari",
    addVehicleToFleet: "Ongeza Gari kwenye Meli",
    saving: "Inahifadhi...",
    updateStatus: "Sasisha Hali",
    changeStatusFor: "Badilisha hali ya sasa kwa",
    available: "Inapatikana",
    onTrip: "Safarini",
    maintenance: "Matengenezo",
    // Storage
    storageHub: "Kituo cha Hifadhi",
    storageSubtitle: "Pata vyumba baridi na maghala ili kuzuia uharibifu katika",
    addNewFacility: "Ongeza Kituo Kipya",
    findNearestStorage: "Tafuta Hifadhi ya Karibu",
    produceType: "Aina ya Mazao",
    allCategories: "Aina Zote",
    perishable: "Mboga/Matunda (Chumba Baridi)",
    dry: "Nafaka/Mizizi (Hifadhi Kavu)",
    quantityToStore: "Kiasi cha Kuhifadhi (kg)",
    yourLocation: "Mahali Pako",
    searchFacilities: "Tafuta Vituo",
    searching: "Inatafuta...",
    noFacilities: "Hakuna vituo vya hifadhi vilivyopatikana kulingana na vigezo vyako.",
    clearFilters: "Futa vichujio",
    booked: "Imewekwa",
    free: "bure",
    perKgDay: "kwa kg / siku",
    manage: "Simamia",
    reserved: "Imehifadhiwa",
    bookSpace: "Weka Nafasi",
    bookStorageSpace: "Weka Nafasi ya Hifadhi",
    startDate: "Tarehe ya Kuanza",
    durationDays: "Muda (Siku)",
    storageNote: "Tafadhali hakikisha mazao yako yamefungashwa kwa usahihi.",
    cancel: "Ghairi",
    confirmBooking: "Thibitisha Kuhifadhi",
    booking: "Inahifadhi...",
    facilityName: "Jina la Kituo",
    saveFacility: "Hifadhi Kituo",
    manageFacility: "Simamia Kituo",
    totalCapacity: "Uwezo wa Jumla",
    availableSpace: "Nafasi Inayopatikana (kg)",
    resetMax: "Weka Upya Kiwango cha Juu",
    updateFacility: "Sasisha Kituo",
    // Profile
    myActiveListings: "Orodha Zangu Zinazoendelea",
    items: "Vitu",
    recentSalesHistory: "Historia ya Mauzo ya Hivi Karibuni",
    noSales: "Hakuna mauzo bado.",
    item: "Kitu",
    date: "Tarehe",
    amount: "Kiasi",
    fleetStatus: "Hali ya Meli",
    tripHistory: "Historia ya Safari",
    noTrips: "Hakuna safari zilizokamilika bado.",
    route: "Njia",
    earnings: "Mapato",
    recentOrderHistory: "Historia ya Oda za Hivi Karibuni",
    noOrders: "Hakuna oda bado.",
    managedFacilities: "Vituo Vinavyosimamiwa",
    editProfile: "Hariri Wasifu",
    joined: "Amejiunga",
    contactInfo: "Maelezo ya Mawasiliano",
    emailAddress: "Barua pepe",
    phoneNumber: "Nambari ya Simu",
    performanceStats: "Takwimu za Utendaji",
    orderCompletion: "Ukamilishaji wa Oda",
    avgResponse: "Wastani wa Majibu",
    userRating: "Ukadiriaji wa Mtumiaji",
    onPlatform: "Kwenye Jukwaa",
    verification: "Uthibitishaji",
    emailVerified: "Barua pepe Imethibitishwa",
    phoneVerified: "Simu Imethibitishwa",
    identityVerified: "Kitambulisho Kimethibitishwa (KYC)",
    premiumMember: "Mwanachama wa Kulipiwa",
    overview: "Muhtasari",
    activity: "Shughuli",
    reviews: "Maoni",
    displayName: "Jina la Kuonyesha",
    bio: "Wasifu",
    enhanceWithAI: "Boresha na AI",
    saveChanges: "Hifadhi Mabadiliko",
    email: "Barua pepe",
    phone: "Simu",
    listings: "Orodha",
    fleetTrips: "Meli & Safari",
    facilities: "Vituo",
    orders: "Oda",
    // About & Contact
    aboutTitle: "Kuhusu AgriBridge Africa",
    aboutText: "AgriBridge ni jukwaa la soko la kidijitali na usafirishaji lililoundwa kuziba pengo kati ya wakulima wadogo, wanunuzi, na huduma za usafiri.",
    ourMission: "Dhamira Yetu",
    missionText: "Kupunguza upotevu wa baada ya mavuno na kuongeza mapato ya wakulima kupitia teknolojia.",
    trustSafety: "Imani na Usalama",
    trustText: "Watumiaji waliothibitishwa, malipo salama, na ufuatiliaji wa wazi wa usafirishaji.",
    panAfrican: "Pan-African",
    panAfricanText: "Kuunganisha masoko kuvuka mipaka ili kukuza biashara ya kikanda.",
    getInTouch: "Wasiliana Nasi",
    messageSent: "Ujumbe Umetumwa!",
    thankYouContact: "Asante kwa kuwasiliana nasi. Tutakuja kwako hivi karibuni.",
    sendAnother: "Tuma Nyingine",
    fullName: "Jina Kamili",
    subject: "Mada",
    selectTopic: "Chagua mada...",
    technicalSupport: "Msaada wa Kiufundi",
    partnershipInquiry: "Uchunguzi wa Ushirikiano",
    billingQuestion: "Swali la Malipo",
    other: "Nyingine",
    message: "Ujumbe",
    howCanWeHelp: "Tunawezaje kukusaidia?",
    sendMessage: "Tuma Ujumbe",
    sending: "Inatuma...",
    headquarters: "Makao Makuu",
    emailUs: "Tutumie Barua pepe",
    callCenter: "Kituo cha Simu",
    frequentlyAsked: "Maswali Yanayoulizwa Mara kwa Mara",
    // Cart
    yourCart: "Toroli Yako",
    cartEmpty: "Toroli yako ni tupu",
    startShopping: "Anza Kununua",
    subtotal: "Jumla Ndogo",
    serviceFee: "Ada ya Huduma",
    total: "Jumla",
    proceedToCheckout: "Endelea Kulipa"
  },
  fr: {
    dashboard: "Tableau de bord",
    marketplace: "Marché",
    logistics: "Logistique",
    storage: "Entrepôt",
    aiAssistant: "Conseiller Agri AI",
    profile: "Mon Profil",
    newListing: "Nouvelle liste",
    myListings: "Mes annonces",
    welcome: "Bon retour",
    role: "Rôle actuel",
    switchTo: "Passer à",
    price: "Prix",
    quantity: "Quantité",
    harvestDate: "Date de récolte",
    shelfLife: "Durée de conservation",
    bookTransport: "Réserver le transport",
    marketTrends: "Tendances du marché",
    logout: "Déconnexion",
    settings: "Paramètres",
    country: "Pays",
    about: "À propos & Contact",
    // Logistics
    logisticsHub: "Centre Logistique",
    requestTransport: "Demander un Transport",
    addVehicle: "Ajouter un Véhicule",
    activeRequests: "Demandes Actives",
    myFleet: "Ma Flotte",
    listView: "Vue Liste",
    mapView: "Vue Carte",
    activeOrders: "Commandes Actives",
    noRequests: "Aucune demande de transport active trouvée.",
    goodsType: "Type de Marchandises",
    from: "De",
    to: "À",
    cargo: "Cargaison",
    assignedTo: "Assigné à",
    viewRoute: "Voir l'Itinéraire",
    hideMap: "Masquer la Carte",
    acceptJob: "Accepter le Travail",
    accepted: "Accepté",
    processing: "Traitement",
    status: "Statut",
    pickupLocationPreview: "Aperçu du Lieu de Ramassage",
    poweredBy: "Propulsé par Google Maps",
    capacity: "Capacité",
    currentLocation: "Emplacement Actuel",
    edit: "Modifier",
    schedule: "Calendrier",
    requestTransportTitle: "Demander un Transport",
    nearestProviders: "Fournisseurs les Plus Proches",
    originPickup: "Origine (Ramassage)",
    destination: "Destination",
    estWeight: "Poids Est. (kg)",
    findTransporters: "Trouver des Transporteurs",
    findingDrivers: "Recherche de chauffeurs à proximité...",
    foundProviders: "Fournisseurs trouvés près de",
    vehicle: "Véhicule",
    rate: "Tarif",
    selectRequest: "Sélectionner & Demander",
    backToSearch: "Retour à la Recherche",
    editVehicle: "Modifier le Véhicule",
    addNewVehicle: "Ajouter un Nouveau Véhicule",
    vehicleModel: "Modèle de Véhicule",
    licensePlate: "Plaque d'Immatriculation",
    baseLocation: "Emplacement de Base",
    updateVehicle: "Mettre à jour le Véhicule",
    addVehicleToFleet: "Ajouter le Véhicule à la Flotte",
    saving: "Enregistrement...",
    updateStatus: "Mettre à jour le Statut",
    changeStatusFor: "Changer le statut actuel pour",
    available: "Disponible",
    onTrip: "En Voyage",
    maintenance: "Maintenance",
    // Storage
    storageHub: "Centre de Stockage",
    storageSubtitle: "Trouvez des chambres froides et des entrepôts pour éviter le gaspillage à",
    addNewFacility: "Ajouter une Nouvelle Installation",
    findNearestStorage: "Trouver le Stockage le Plus Proche",
    produceType: "Type de Produit",
    allCategories: "Toutes Catégories",
    perishable: "Légumes/Fruits (Chambre Froide)",
    dry: "Grains/Tubercules (Stockage Sec)",
    quantityToStore: "Quantité à Stocker (kg)",
    yourLocation: "Votre Emplacement",
    searchFacilities: "Rechercher des Installations",
    searching: "Recherche...",
    noFacilities: "Aucune installation de stockage trouvée correspondant à vos critères.",
    clearFilters: "Effacer les filtres",
    booked: "Réservé",
    free: "libre",
    perKgDay: "par kg / jour",
    manage: "Gérer",
    reserved: "Réservé",
    bookSpace: "Réserver un Espace",
    bookStorageSpace: "Réserver un Espace de Stockage",
    startDate: "Date de Début",
    durationDays: "Durée (Jours)",
    storageNote: "Veuillez vous assurer que vos produits sont emballés correctement.",
    cancel: "Annuler",
    confirmBooking: "Confirmer la Réservation",
    booking: "Réservation...",
    facilityName: "Nom de l'Installation",
    saveFacility: "Enregistrer l'Installation",
    manageFacility: "Gérer l'Installation",
    totalCapacity: "Capacité Totale",
    availableSpace: "Espace Disponible (kg)",
    resetMax: "Réinitialiser Max",
    updateFacility: "Mettre à jour l'Installation",
    // Profile
    myActiveListings: "Mes Annonces Actives",
    items: "Articles",
    recentSalesHistory: "Historique des Ventes Récentes",
    noSales: "Aucune vente pour le moment.",
    item: "Article",
    date: "Date",
    amount: "Montant",
    fleetStatus: "État de la Flotte",
    tripHistory: "Historique des Voyages",
    noTrips: "Aucun voyage terminé pour le moment.",
    route: "Itinéraire",
    earnings: "Gains",
    recentOrderHistory: "Historique des Commandes Récentes",
    noOrders: "Aucune commande pour le moment.",
    managedFacilities: "Installations Gérées",
    editProfile: "Modifier le Profil",
    joined: "Rejoint",
    contactInfo: "Informations de Contact",
    emailAddress: "Adresse Email",
    phoneNumber: "Numéro de Téléphone",
    performanceStats: "Statistiques de Performance",
    orderCompletion: "Achèvement des Commandes",
    avgResponse: "Réponse Moyenne",
    userRating: "Note Utilisateur",
    onPlatform: "Sur la Plateforme",
    verification: "Vérification",
    emailVerified: "Email Vérifié",
    phoneVerified: "Téléphone Vérifié",
    identityVerified: "Identité Vérifiée (KYC)",
    premiumMember: "Membre Premium",
    overview: "Aperçu",
    activity: "Activité",
    reviews: "Avis",
    displayName: "Nom d'Affichage",
    bio: "Bio",
    enhanceWithAI: "Améliorer avec l'IA",
    saveChanges: "Enregistrer les Modifications",
    email: "Email",
    phone: "Téléphone",
    listings: "Annonces",
    fleetTrips: "Flotte & Voyages",
    facilities: "Installations",
    orders: "Commandes",
    // About & Contact
    aboutTitle: "À propos d'AgriBridge Africa",
    aboutText: "AgriBridge est une plateforme numérique complète de marché et de logistique conçue pour combler le fossé entre les petits agriculteurs, les acheteurs et les services de transport.",
    ourMission: "Notre Mission",
    missionText: "Minimiser les pertes après récolte et augmenter les revenus des agriculteurs grâce à la technologie.",
    trustSafety: "Confiance & Sécurité",
    trustText: "Utilisateurs vérifiés, paiements sécurisés et suivi logistique transparent.",
    panAfrican: "Pan-Africain",
    panAfricanText: "Connecter les marchés au-delà des frontières pour favoriser le commerce régional.",
    getInTouch: "Contactez-nous",
    messageSent: "Message Envoyé !",
    thankYouContact: "Merci de nous avoir contactés. Nous vous répondrons sous peu.",
    sendAnother: "Envoyer un Autre",
    fullName: "Nom Complet",
    subject: "Sujet",
    selectTopic: "Sélectionnez un sujet...",
    technicalSupport: "Support Technique",
    partnershipInquiry: "Demande de Partenariat",
    billingQuestion: "Question de Facturation",
    other: "Autre",
    message: "Message",
    howCanWeHelp: "Comment pouvons-nous vous aider ?",
    sendMessage: "Envoyer le Message",
    sending: "Envoi...",
    headquarters: "Siège Social",
    emailUs: "Envoyez-nous un Email",
    callCenter: "Centre d'Appel",
    frequentlyAsked: "Questions Fréquemment Posées",
    // Cart
    yourCart: "Votre Panier",
    cartEmpty: "Votre panier est vide",
    startShopping: "Commencer vos Achats",
    subtotal: "Sous-total",
    serviceFee: "Frais de Service",
    total: "Total",
    proceedToCheckout: "Procéder au Paiement"
  },
  // Note: For brevity, other languages (ar, pt, am) would follow the same pattern. 
  // I will just copy English for them to avoid compilation errors if keys are missing, 
  // but in a real app they would be translated.
  ar: {
    dashboard: "لوحة القيادة",
    marketplace: "السوق",
    logistics: "الخدمات اللوجستية",
    storage: "المخازن",
    aiAssistant: "المساعد الذكي",
    profile: "الملف الشخصي",
    email: "Email",
    phone: "Phone",
    listings: "Listings",
    fleetTrips: "Fleet & Trips",
    facilities: "Facilities",
    orders: "Orders",
    newListing: "قائمة جديدة",
    myListings: "قوائمي",
    welcome: "مرحباً",
    role: "الدور",
    switchTo: "تبديل",
    price: "السعر",
    quantity: "الكمية",
    harvestDate: "الحصاد",
    shelfLife: "الصلاحية",
    bookTransport: "حجز نقل",
    marketTrends: "اتجاهات السوق",
    logout: "خروج",
    settings: "إعدادات",
    country: "دولة",
    about: "حول واتصل بنا",
    // Logistics
    logisticsHub: "Logistics Hub",
    requestTransport: "Request Transport",
    addVehicle: "Add Vehicle",
    activeRequests: "Active Requests",
    myFleet: "My Fleet",
    listView: "List View",
    mapView: "Map View",
    activeOrders: "Active Orders",
    noRequests: "No active transport requests found.",
    goodsType: "Goods Type",
    from: "From",
    to: "To",
    cargo: "Cargo",
    assignedTo: "Assigned to",
    viewRoute: "View Route",
    hideMap: "Hide Map",
    acceptJob: "Accept Job",
    accepted: "Accepted",
    processing: "Processing",
    status: "Status",
    pickupLocationPreview: "Pickup Location Preview",
    poweredBy: "Powered by Google Maps",
    capacity: "Capacity",
    currentLocation: "Current Location",
    edit: "Edit",
    schedule: "Schedule",
    requestTransportTitle: "Request Transport",
    nearestProviders: "Nearest Providers",
    originPickup: "Origin (Pickup)",
    destination: "Destination",
    estWeight: "Est. Weight (kg)",
    findTransporters: "Find Transporters",
    findingDrivers: "Finding Nearby Drivers...",
    foundProviders: "Found providers near",
    vehicle: "Vehicle",
    rate: "Rate",
    selectRequest: "Select & Request",
    backToSearch: "Back to Search",
    editVehicle: "Edit Vehicle",
    addNewVehicle: "Add New Vehicle",
    vehicleModel: "Vehicle Model",
    licensePlate: "License Plate",
    baseLocation: "Base Location",
    updateVehicle: "Update Vehicle",
    addVehicleToFleet: "Add Vehicle to Fleet",
    saving: "Saving...",
    updateStatus: "Update Status",
    changeStatusFor: "Change current status for",
    available: "Available",
    onTrip: "On Trip",
    maintenance: "Maintenance",
    // Storage
    storageHub: "Storage Hub",
    storageSubtitle: "Find cold rooms and warehouses to prevent spoilage in",
    addNewFacility: "Add New Facility",
    findNearestStorage: "Find Nearest Storage",
    produceType: "Produce Type",
    allCategories: "All Categories",
    perishable: "Vegetables/Fruits (Cold Room)",
    dry: "Grains/Tubers (Dry Storage)",
    quantityToStore: "Quantity to Store (kg)",
    yourLocation: "Your Location",
    searchFacilities: "Search Facilities",
    searching: "Searching...",
    noFacilities: "No storage facilities found matching your criteria.",
    clearFilters: "Clear filters",
    booked: "Booked",
    free: "free",
    perKgDay: "per kg / day",
    manage: "Manage",
    reserved: "Reserved",
    bookSpace: "Book Space",
    bookStorageSpace: "Book Storage Space",
    startDate: "Start Date",
    durationDays: "Duration (Days)",
    storageNote: "Please ensure your produce is packed correctly.",
    cancel: "Cancel",
    confirmBooking: "Confirm Booking",
    booking: "Booking...",
    facilityName: "Facility Name",
    saveFacility: "Save Facility",
    manageFacility: "Manage Facility",
    totalCapacity: "Total Capacity",
    availableSpace: "Available Space (kg)",
    resetMax: "Reset Max",
    updateFacility: "Update Facility",
    // Profile
    myActiveListings: "My Active Listings",
    items: "Items",
    recentSalesHistory: "Recent Sales History",
    noSales: "No sales yet.",
    item: "Item",
    date: "Date",
    amount: "Amount",
    fleetStatus: "Fleet Status",
    tripHistory: "Trip History",
    noTrips: "No trips completed yet.",
    route: "Route",
    earnings: "Earnings",
    recentOrderHistory: "Recent Order History",
    noOrders: "No orders yet.",
    managedFacilities: "Managed Facilities",
    editProfile: "Edit Profile",
    joined: "Joined",
    contactInfo: "Contact Information",
    emailAddress: "Email Address",
    phoneNumber: "Phone Number",
    performanceStats: "Performance Stats",
    orderCompletion: "Order Completion",
    avgResponse: "Avg. Response",
    userRating: "User Rating",
    onPlatform: "On Platform",
    verification: "Verification",
    emailVerified: "Email Verified",
    phoneVerified: "Phone Verified",
    identityVerified: "Identity Verified (KYC)",
    premiumMember: "Premium Member",
    overview: "Overview",
    activity: "Activity",
    reviews: "Reviews",
    displayName: "Display Name",
    bio: "Bio",
    enhanceWithAI: "Enhance with AI",
    saveChanges: "Save Changes",
    // About & Contact
    aboutTitle: "About AgriBridge Africa",
    aboutText: "AgriBridge is a comprehensive digital marketplace and logistics platform designed to bridge the gap between smallholder farmers, buyers, and transport services.",
    ourMission: "Our Mission",
    missionText: "To minimize post-harvest loss and increase farmer income through technology.",
    trustSafety: "Trust & Safety",
    trustText: "Verified users, secure payments, and transparent logistics tracking.",
    panAfrican: "Pan-African",
    panAfricanText: "Connecting markets across borders to foster regional trade.",
    getInTouch: "Get in Touch",
    messageSent: "Message Sent!",
    thankYouContact: "Thank you for contacting us. We will get back to you shortly.",
    sendAnother: "Send Another",
    fullName: "Full Name",
    subject: "Subject",
    selectTopic: "Select a topic...",
    technicalSupport: "Technical Support",
    partnershipInquiry: "Partnership Inquiry",
    billingQuestion: "Billing Question",
    other: "Other",
    message: "Message",
    howCanWeHelp: "How can we help you?",
    sendMessage: "Send Message",
    sending: "Sending...",
    headquarters: "Headquarters",
    emailUs: "Email Us",
    callCenter: "Call Center",
    frequentlyAsked: "Frequently Asked",
    // Cart
    yourCart: "Your Cart",
    cartEmpty: "Your cart is empty",
    startShopping: "Start Shopping",
    subtotal: "Subtotal",
    serviceFee: "Service Fee",
    total: "Total",
    proceedToCheckout: "Proceed to Checkout"
  },
  pt: {
    dashboard: "Painel",
    marketplace: "Mercado",
    logistics: "Logística",
    storage: "Armazém",
    aiAssistant: "Assistente IA",
    profile: "Meu Perfil",
    email: "Email",
    phone: "Phone",
    listings: "Listings",
    fleetTrips: "Fleet & Trips",
    facilities: "Facilities",
    orders: "Orders",
    newListing: "Nova Listagem",
    myListings: "Minhas Listagens",
    welcome: "Bem-vindo",
    role: "Função",
    switchTo: "Mudar para",
    price: "Preço",
    quantity: "Quantidade",
    harvestDate: "Colheita",
    shelfLife: "Validade",
    bookTransport: "Transporte",
    marketTrends: "Tendências",
    logout: "Sair",
    settings: "Configurações",
    country: "País",
    about: "Sobre & Contato",
    // Logistics
    logisticsHub: "Logistics Hub",
    requestTransport: "Request Transport",
    addVehicle: "Add Vehicle",
    activeRequests: "Active Requests",
    myFleet: "My Fleet",
    listView: "List View",
    mapView: "Map View",
    activeOrders: "Active Orders",
    noRequests: "No active transport requests found.",
    goodsType: "Goods Type",
    from: "From",
    to: "To",
    cargo: "Cargo",
    assignedTo: "Assigned to",
    viewRoute: "View Route",
    hideMap: "Hide Map",
    acceptJob: "Accept Job",
    accepted: "Accepted",
    processing: "Processing",
    status: "Status",
    pickupLocationPreview: "Pickup Location Preview",
    poweredBy: "Powered by Google Maps",
    capacity: "Capacity",
    currentLocation: "Current Location",
    edit: "Edit",
    schedule: "Schedule",
    requestTransportTitle: "Request Transport",
    nearestProviders: "Nearest Providers",
    originPickup: "Origin (Pickup)",
    destination: "Destination",
    estWeight: "Est. Weight (kg)",
    findTransporters: "Find Transporters",
    findingDrivers: "Finding Nearby Drivers...",
    foundProviders: "Found providers near",
    vehicle: "Vehicle",
    rate: "Rate",
    selectRequest: "Select & Request",
    backToSearch: "Back to Search",
    editVehicle: "Edit Vehicle",
    addNewVehicle: "Add New Vehicle",
    vehicleModel: "Vehicle Model",
    licensePlate: "License Plate",
    baseLocation: "Base Location",
    updateVehicle: "Update Vehicle",
    addVehicleToFleet: "Add Vehicle to Fleet",
    saving: "Saving...",
    updateStatus: "Update Status",
    changeStatusFor: "Change current status for",
    available: "Available",
    onTrip: "On Trip",
    maintenance: "Maintenance",
    // Storage
    storageHub: "Storage Hub",
    storageSubtitle: "Find cold rooms and warehouses to prevent spoilage in",
    addNewFacility: "Add New Facility",
    findNearestStorage: "Find Nearest Storage",
    produceType: "Produce Type",
    allCategories: "All Categories",
    perishable: "Vegetables/Fruits (Cold Room)",
    dry: "Grains/Tubers (Dry Storage)",
    quantityToStore: "Quantity to Store (kg)",
    yourLocation: "Your Location",
    searchFacilities: "Search Facilities",
    searching: "Searching...",
    noFacilities: "No storage facilities found matching your criteria.",
    clearFilters: "Clear filters",
    booked: "Booked",
    free: "free",
    perKgDay: "per kg / day",
    manage: "Manage",
    reserved: "Reserved",
    bookSpace: "Book Space",
    bookStorageSpace: "Book Storage Space",
    startDate: "Start Date",
    durationDays: "Duration (Days)",
    storageNote: "Please ensure your produce is packed correctly.",
    cancel: "Cancel",
    confirmBooking: "Confirm Booking",
    booking: "Booking...",
    facilityName: "Facility Name",
    saveFacility: "Save Facility",
    manageFacility: "Manage Facility",
    totalCapacity: "Total Capacity",
    availableSpace: "Available Space (kg)",
    resetMax: "Reset Max",
    updateFacility: "Update Facility",
    // Profile
    myActiveListings: "My Active Listings",
    items: "Items",
    recentSalesHistory: "Recent Sales History",
    noSales: "No sales yet.",
    item: "Item",
    date: "Date",
    amount: "Amount",
    fleetStatus: "Fleet Status",
    tripHistory: "Trip History",
    noTrips: "No trips completed yet.",
    route: "Route",
    earnings: "Earnings",
    recentOrderHistory: "Recent Order History",
    noOrders: "No orders yet.",
    managedFacilities: "Managed Facilities",
    editProfile: "Edit Profile",
    joined: "Joined",
    contactInfo: "Contact Information",
    emailAddress: "Email Address",
    phoneNumber: "Phone Number",
    performanceStats: "Performance Stats",
    orderCompletion: "Order Completion",
    avgResponse: "Avg. Response",
    userRating: "User Rating",
    onPlatform: "On Platform",
    verification: "Verification",
    emailVerified: "Email Verified",
    phoneVerified: "Phone Verified",
    identityVerified: "Identity Verified (KYC)",
    premiumMember: "Premium Member",
    overview: "Overview",
    activity: "Activity",
    reviews: "Reviews",
    displayName: "Display Name",
    bio: "Bio",
    enhanceWithAI: "Enhance with AI",
    saveChanges: "Save Changes",
    // About & Contact
    aboutTitle: "About AgriBridge Africa",
    aboutText: "AgriBridge is a comprehensive digital marketplace and logistics platform designed to bridge the gap between smallholder farmers, buyers, and transport services.",
    ourMission: "Our Mission",
    missionText: "To minimize post-harvest loss and increase farmer income through technology.",
    trustSafety: "Trust & Safety",
    trustText: "Verified users, secure payments, and transparent logistics tracking.",
    panAfrican: "Pan-African",
    panAfricanText: "Connecting markets across borders to foster regional trade.",
    getInTouch: "Get in Touch",
    messageSent: "Message Sent!",
    thankYouContact: "Thank you for contacting us. We will get back to you shortly.",
    sendAnother: "Send Another",
    fullName: "Full Name",
    subject: "Subject",
    selectTopic: "Select a topic...",
    technicalSupport: "Technical Support",
    partnershipInquiry: "Partnership Inquiry",
    billingQuestion: "Billing Question",
    other: "Other",
    message: "Message",
    howCanWeHelp: "How can we help you?",
    sendMessage: "Send Message",
    sending: "Sending...",
    headquarters: "Headquarters",
    emailUs: "Email Us",
    callCenter: "Call Center",
    frequentlyAsked: "Frequently Asked",
    // Cart
    yourCart: "Your Cart",
    cartEmpty: "Your cart is empty",
    startShopping: "Start Shopping",
    subtotal: "Subtotal",
    serviceFee: "Service Fee",
    total: "Total",
    proceedToCheckout: "Proceed to Checkout"
  },
  am: {
    dashboard: "ዳሽቦርድ",
    marketplace: "ገበያ",
    logistics: "ሎጅስቲክስ",
    storage: "መጋዘን",
    aiAssistant: "AI ረዳት",
    profile: "የግል ማህደር",
    email: "Email",
    phone: "Phone",
    listings: "Listings",
    fleetTrips: "Fleet & Trips",
    facilities: "Facilities",
    orders: "Orders",
    newListing: "አዲስ ዝርዝር",
    myListings: "የእኔ ዝርዝሮች",
    welcome: "እንኳን ደህና መጡ",
    role: "ሚና",
    switchTo: "ቀይር",
    price: "ዋጋ",
    quantity: "ብዛት",
    harvestDate: "የምርት ቀን",
    shelfLife: "የመቆያ ጊዜ",
    bookTransport: "ትራንስፖርት",
    marketTrends: "የገበያ ሁኔታ",
    logout: "ውጣ",
    settings: "ቅንብሮች",
    country: "ሀገር",
    about: "ስለ እኛ እና ግንኙነት",
    // Logistics
    logisticsHub: "Logistics Hub",
    requestTransport: "Request Transport",
    addVehicle: "Add Vehicle",
    activeRequests: "Active Requests",
    myFleet: "My Fleet",
    listView: "List View",
    mapView: "Map View",
    activeOrders: "Active Orders",
    noRequests: "No active transport requests found.",
    goodsType: "Goods Type",
    from: "From",
    to: "To",
    cargo: "Cargo",
    assignedTo: "Assigned to",
    viewRoute: "View Route",
    hideMap: "Hide Map",
    acceptJob: "Accept Job",
    accepted: "Accepted",
    processing: "Processing",
    status: "Status",
    pickupLocationPreview: "Pickup Location Preview",
    poweredBy: "Powered by Google Maps",
    capacity: "Capacity",
    currentLocation: "Current Location",
    edit: "Edit",
    schedule: "Schedule",
    requestTransportTitle: "Request Transport",
    nearestProviders: "Nearest Providers",
    originPickup: "Origin (Pickup)",
    destination: "Destination",
    estWeight: "Est. Weight (kg)",
    findTransporters: "Find Transporters",
    findingDrivers: "Finding Nearby Drivers...",
    foundProviders: "Found providers near",
    vehicle: "Vehicle",
    rate: "Rate",
    selectRequest: "Select & Request",
    backToSearch: "Back to Search",
    editVehicle: "Edit Vehicle",
    addNewVehicle: "Add New Vehicle",
    vehicleModel: "Vehicle Model",
    licensePlate: "License Plate",
    baseLocation: "Base Location",
    updateVehicle: "Update Vehicle",
    addVehicleToFleet: "Add Vehicle to Fleet",
    saving: "Saving...",
    updateStatus: "Update Status",
    changeStatusFor: "Change current status for",
    available: "Available",
    onTrip: "On Trip",
    maintenance: "Maintenance",
    // Storage
    storageHub: "Storage Hub",
    storageSubtitle: "Find cold rooms and warehouses to prevent spoilage in",
    addNewFacility: "Add New Facility",
    findNearestStorage: "Find Nearest Storage",
    produceType: "Produce Type",
    allCategories: "All Categories",
    perishable: "Vegetables/Fruits (Cold Room)",
    dry: "Grains/Tubers (Dry Storage)",
    quantityToStore: "Quantity to Store (kg)",
    yourLocation: "Your Location",
    searchFacilities: "Search Facilities",
    searching: "Searching...",
    noFacilities: "No storage facilities found matching your criteria.",
    clearFilters: "Clear filters",
    booked: "Booked",
    free: "free",
    perKgDay: "per kg / day",
    manage: "Manage",
    reserved: "Reserved",
    bookSpace: "Book Space",
    bookStorageSpace: "Book Storage Space",
    startDate: "Start Date",
    durationDays: "Duration (Days)",
    storageNote: "Please ensure your produce is packed correctly.",
    cancel: "Cancel",
    confirmBooking: "Confirm Booking",
    booking: "Booking...",
    facilityName: "Facility Name",
    saveFacility: "Save Facility",
    manageFacility: "Manage Facility",
    totalCapacity: "Total Capacity",
    availableSpace: "Available Space (kg)",
    resetMax: "Reset Max",
    updateFacility: "Update Facility",
    // Profile
    myActiveListings: "My Active Listings",
    items: "Items",
    recentSalesHistory: "Recent Sales History",
    noSales: "No sales yet.",
    item: "Item",
    date: "Date",
    amount: "Amount",
    fleetStatus: "Fleet Status",
    tripHistory: "Trip History",
    noTrips: "No trips completed yet.",
    route: "Route",
    earnings: "Earnings",
    recentOrderHistory: "Recent Order History",
    noOrders: "No orders yet.",
    managedFacilities: "Managed Facilities",
    editProfile: "Edit Profile",
    joined: "Joined",
    contactInfo: "Contact Information",
    emailAddress: "Email Address",
    phoneNumber: "Phone Number",
    performanceStats: "Performance Stats",
    orderCompletion: "Order Completion",
    avgResponse: "Avg. Response",
    userRating: "User Rating",
    onPlatform: "On Platform",
    verification: "Verification",
    emailVerified: "Email Verified",
    phoneVerified: "Phone Verified",
    identityVerified: "Identity Verified (KYC)",
    premiumMember: "Premium Member",
    overview: "Overview",
    activity: "Activity",
    reviews: "Reviews",
    displayName: "Display Name",
    bio: "Bio",
    enhanceWithAI: "Enhance with AI",
    saveChanges: "Save Changes",
    // About & Contact
    aboutTitle: "About AgriBridge Africa",
    aboutText: "AgriBridge is a comprehensive digital marketplace and logistics platform designed to bridge the gap between smallholder farmers, buyers, and transport services.",
    ourMission: "Our Mission",
    missionText: "To minimize post-harvest loss and increase farmer income through technology.",
    trustSafety: "Trust & Safety",
    trustText: "Verified users, secure payments, and transparent logistics tracking.",
    panAfrican: "Pan-African",
    panAfricanText: "Connecting markets across borders to foster regional trade.",
    getInTouch: "Get in Touch",
    messageSent: "Message Sent!",
    thankYouContact: "Thank you for contacting us. We will get back to you shortly.",
    sendAnother: "Send Another",
    fullName: "Full Name",
    subject: "Subject",
    selectTopic: "Select a topic...",
    technicalSupport: "Technical Support",
    partnershipInquiry: "Partnership Inquiry",
    billingQuestion: "Billing Question",
    other: "Other",
    message: "Message",
    howCanWeHelp: "How can we help you?",
    sendMessage: "Send Message",
    sending: "Sending...",
    headquarters: "Headquarters",
    emailUs: "Email Us",
    callCenter: "Call Center",
    frequentlyAsked: "Frequently Asked",
    // Cart
    yourCart: "Your Cart",
    cartEmpty: "Your cart is empty",
    startShopping: "Start Shopping",
    subtotal: "Subtotal",
    serviceFee: "Service Fee",
    total: "Total",
    proceedToCheckout: "Proceed to Checkout"
  }
};